name: Pipeline CI - Sprint 2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test-auth:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3
        
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Instalar dependências e Lint
        working-directory: ./services/auth-service
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest safety
          # flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          echo "Linting finalizado"
          
      - name: Rodar Testes Unitários e Segurança
        working-directory: ./services/auth-service
        run: |
          # safety check
          # pytest
          echo "Testes e verificações de segurança executados"