services:
  auth-service:
    build: 
      context: ../services/auth-service
    ports:
      - "8081:8081"

  academic-service:
    build: 
      context: ../services/academic-service
    ports:
      - "8082:8082"

  assignment-service:
    build: 
      context: ../services/assignment-service
    ports:
      - "8083:8083"