name: CD - Assignment Service

on:
  push:
    branches: [ "main" ]
    paths:
      - 'plataforma/services/assignment-service/**' # Vigia apenas esta pasta!

jobs:
  deploy-assignment:
    name: 🚀 Deploy Assignment Service
    runs-on: ubuntu-latest
    steps:
      - name: Disparar Webhook no Render
        run: curl -X POST ${{ secrets.RENDER_HOOK_ASSIGNMENT }}